app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/amigoscode
      password: 'LaunchMobility1'
      pool-size: 30
      username: lmadmin

server:
  error:
    include-binding-errors: always
    include-message: always


